# -*- coding: utf-8 -*-
"""metro_all.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gx8YkLHmQT11RUMcWCX5GvPFT4zflrxI
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Load the data
data = pd.read_csv("all(opt).csv")
data['datetime'] = pd.to_datetime(data['datetime']).dt.strftime('%Y-%m-%d %H:00:00')
data.info()

metro = pd.read_csv("loadmetro.csv")
metro.drop("Load", axis=1, inplace=True)
metro.info()

merged_df = data.merge(metro, on='datetime')
#merged_df

merged_df.info()

merged_df.set_index('datetime', inplace=True)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(25, 15))

# Calculate correlation matrix
corr_matrix = merged_df.corr()

# Create a triangular mask for upper diagonal
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

# Create a heatmap plot of correlation values
sns.heatmap(corr_matrix, annot=True, cmap='RdYlBu', mask=mask)
plt.title('Correlation Heatmap')
plt.show()

# Reset the index
newdf2_reset = merged_df.reset_index()

# Save data to CSV
newdf2_reset.to_csv('metro_all.csv', index=False)

newdf2_reset