# -*- coding: utf-8 -*-
"""load_metro(2019-2021).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14AWZs44VAGkGDw7TOFGHjsdk7YIrzNzs
"""

import pandas as pd

load=pd.read_csv("98+99+400-ver2.csv" )
metro=pd.read_csv("meteorological_data.csv" )

load.columns=['datetime','Load']
load

metro

merged_df = metro.merge(load, on='datetime')
merged_df

merged_df.to_csv('load_metro(2019-2021).csv',  index = None)