# -*- coding: utf-8 -*-
"""meteorological data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YW66HzF5w9MKD553BuGKovJA775Tpc5Z

# RH2M +	PRECTOTCORR +	WS50M +	WS10M +	ALLSKY_KT
"""

import pandas as pd
from datetime import datetime
from pandas import DataFrame
from pandas import read_csv
df=pd.read_csv("RH2M+PRECTOTCORR+WS50M+WS10M+ALLSKY_KT.csv" )
df

#year
df['YEAR'] = pd.to_datetime(df['YEAR'], format='%Y')
df['year'] = df['YEAR'].dt.year

#month
df['MO'] = pd.to_datetime(df['MO'], format='%m')
df['month'] = df['MO'].dt.month

#day
df['DY'] = pd.to_datetime(df['DY'], format='%d')
df['day'] = df['DY'].dt.day


#hour
df['HR'] = pd.to_datetime(df['HR'], format='%H')
df['hour'] = df['HR'].dt.hour


#Drop the unnecessary columns
columns_to_drop = ['YEAR', 'MO', 'DY', 'HR']
df = df.drop(columns=columns_to_drop)
df

df.dtypes

df['datetime'] = pd.to_datetime(df[['year', 'month', 'day']]) + pd.to_timedelta(df['hour'], unit='h')
df.head(5)

columns_to_drop2 = ['year', 'month', 'day', 'hour']
df = df.drop(columns=columns_to_drop2)

# Move the last column to the first position
last_column = df.pop(df.columns[-1])
df.insert(0, last_column.name, last_column)

# Print the updated DataFrame
df.head(5)

df.to_csv('RH2M+PRECTOTCORR+WS50M+WS10M+ALLSKY_KT(Organized).csv',  index = None)

"""# Temperatures"""

import pandas as pd
from datetime import datetime
from pandas import DataFrame
from pandas import read_csv
df=pd.read_csv("Temperatures.csv" )
df

#year
df['YEAR'] = pd.to_datetime(df['YEAR'], format='%Y')
df['year'] = df['YEAR'].dt.year

#month
df['MO'] = pd.to_datetime(df['MO'], format='%m')
df['month'] = df['MO'].dt.month

#day
df['DY'] = pd.to_datetime(df['DY'], format='%d')
df['day'] = df['DY'].dt.day


#hour
df['HR'] = pd.to_datetime(df['HR'], format='%H')
df['hour'] = df['HR'].dt.hour


#Drop the unnecessary columns
columns_to_drop = ['YEAR', 'MO', 'DY', 'HR']
df = df.drop(columns=columns_to_drop)


df['datetime'] = pd.to_datetime(df[['year', 'month', 'day']]) + pd.to_timedelta(df['hour'], unit='h')
columns_to_drop2 = ['year', 'month', 'day', 'hour']
df = df.drop(columns=columns_to_drop2)

# Move the last column to the first position
last_column = df.pop(df.columns[-1])
df.insert(0, last_column.name, last_column)

# Print the updated DataFrame
df.head(5)

df.to_csv('Temperatures(Organized).csv',  index = None)

"""# Merge"""

Temp=pd.read_csv("Temperatures(Organized).csv" )
others=pd.read_csv("RH2M+PRECTOTCORR+WS50M+WS10M+ALLSKY_KT(Organized).csv" )
merged_df = pd.merge(Temp, others, on='datetime')
merged_df

merged_df.to_csv('meteorological data.csv',  index = None)