# -*- coding: utf-8 -*-
"""metro_merged.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DnyHeyVAbqNquZO7Pah0WQSVh7FTvKMS
"""

import pandas as pd
from datetime import datetime
from pandas import DataFrame
from pandas import read_csv

file_names = ["1 (1).csv", "1 (2).csv", "1 (3).csv", "1 (4).csv", "1 (5).csv"]

# Create an empty list to store the processed dataframes
processed_dfs = []

# Loop through the file names
for file_name in file_names:
    # Read the CSV file into a dataframe
    df = pd.read_csv(file_name)

    # Process the dataframe

    # Convert 'YEAR' column to datetime format with year only
    df['YEAR'] = pd.to_datetime(df['YEAR'], format='%Y')

    # Extract the year from the 'YEAR' column
    df['year'] = df['YEAR'].dt.year

    # Convert 'MO' column to datetime format with month only
    df['MO'] = pd.to_datetime(df['MO'], format='%m')

    # Extract the month from the 'MO' column
    df['month'] = df['MO'].dt.month

    # Convert 'DY' column to datetime format with day only
    df['DY'] = pd.to_datetime(df['DY'], format='%d')

    # Extract the day from the 'DY' column
    df['day'] = df['DY'].dt.day

    # Convert 'HR' column to datetime format with hour only
    df['HR'] = pd.to_datetime(df['HR'], format='%H')

    # Extract the hour from the 'HR' column
    df['hour'] = df['HR'].dt.hour

    # Drop unnecessary columns ['YEAR', 'MO', 'DY', 'HR']
    columns_to_drop = ['YEAR', 'MO', 'DY', 'HR']
    df = df.drop(columns=columns_to_drop)

    # Create a new 'datetime' column by combining year, month, day, and hour
    df['datetime'] = pd.to_datetime(df[['year', 'month', 'day']]) + pd.to_timedelta(df['hour'], unit='h')

    # Drop the individual year, month, day, and hour columns
    columns_to_drop2 = ['year', 'month', 'day', 'hour']
    df = df.drop(columns=columns_to_drop2)

    # Move the last column to the first position
    last_column = df.pop(df.columns[-1])
    df.insert(0, last_column.name, last_column)

    # Append the processed dataframe to the list
    processed_dfs.append(df)

processed_dfs[4]

"""# Merge"""

merged_df = pd.merge(processed_dfs[0], processed_dfs[1], on='datetime', how='inner')
merged_df = pd.merge(merged_df, processed_dfs[2], on='datetime', how='inner')
merged_df = pd.merge(merged_df, processed_dfs[3], on='datetime', how='inner')
merged_df = pd.merge(merged_df, processed_dfs[4], on='datetime', how='inner')

merged_df

merged_df.dtypes

merged_df.to_csv('metro_merged.csv',  index = None)